# Generated by Django 3.1.1 on 2020-10-02 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='date',
        ),
        migrations.AddField(
            model_name='listing',
            name='datetime',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
