# Generated by Django 3.1.1 on 2020-10-02 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201002_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='datetime',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
