# Generated by Django 3.1.3 on 2020-11-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201117_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='final_bid',
            new_name='bid',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='start_bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='starting_price',
            field=models.FloatField(default=0),
        ),
    ]
