# Generated by Django 3.1.3 on 2020-11-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201119_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='last_price',
            field=models.FloatField(default=0),
        ),
    ]
