# Generated by Django 3.1.3 on 2020-11-21 04:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_last_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='datetime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
