# Generated by Django 3.1.3 on 2020-11-21 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201120_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='datetime',
            field=models.DateField(default=datetime.datetime(2020, 11, 21, 4, 59, 59, 830052)),
        ),
    ]
