# Generated by Django 3.1.3 on 2020-11-21 05:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201121_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='datetime',
            field=models.DateField(default=datetime.datetime(2020, 11, 21, 5, 2, 7, 757603, tzinfo=utc)),
        ),
    ]
