# Generated by Django 3.1.3 on 2020-11-21 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201121_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
